[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:soldi-api]
command=python -m uvicorn main:app --host 0.0.0.0 --port 3001
directory=/app/soldi-api
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:soldi-website]
command=node server.js
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
